# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@master
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ 97ed59e9-ace7-4150-865c-6321879dc84e }}
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
        
    - name: Install dependencies 
      run: npm install

    - name: Build
      run: npm run build --if-present

    - name: Run the tests and generate coverage report  
      run: npm test -- --coverage

  
